// 用户模块事件
export const GET_WECHAT_USERINFO = 'GET_WECHAT_USERINFO'
export const GET_LOGIN_DATA = 'GET_LOGIN_DATA'
export const GET_DINGDONG_USERINFO = 'GET_DINGDONG_USERINFO'

// 设备模块
export const GET_BINDED_DEVICE = 'GET_BINDED_DEVICE'
export const BINGING_DEVICE_INFO = 'BINGING_DEVICE_INFO'
// 净水模块

// 余额
export const GET_BALANCE = 'GET_BALANCE'
